export const AUTH_SAVE_TOKEN = 'AUTH_SAVE_TOKEN';
export const AUTH_LOAD_FINISH = 'AUTH_LOAD_FINISH';
export const AUTH_CLEAR_TOKEN = 'AUTH_CLEAR_TOKEN';

export const LOAD_FAVOURITES = 'LOAD_FAVOURITES';
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES';
export const REFRESH_FAVOURITES = 'REFRESH_FAVOURITES';
export const ADD_ARTIST = 'ADD_ARTIST';
export const REMOVE_ARTIST = 'REMOVE_ARTIST';
export const ADD_ALBUM = 'ADD_ALBUM';
export const REMOVE_ALBUM = 'REMOVE_ALBUM';

export const LOAD_PLAYLISTS = 'LOAD_PLAYLISTS';
export const PLAYLIST_START = 'PLAYLIST_START';
export const PLAYLIST_ADD = 'PLAYLIST_ADD';
export const PLAYLIST_ADD_SONG = 'PLAYLIST_ADD_SONG';
export const PLAYLIST_DELETE = 'PLAYLIST_DELETE';
export const PLAYLIST_DELETE_SONG = 'PLAYLIST_DELETE_SONG';
export const PLAYLIST_CANCEL = 'PLAYLIST_CANCEL';
