export const LOAD_FAVOURITES = 'LOAD_FAVOURITES';
export const ADD_ARTIST = 'ADD_ARTIST';
export const REMOVE_ARTIST = 'REMOVE_ARTIST';
export const ADD_ALBUM = 'ADD_ALBUM';
export const REMOVE_ALBUM = 'REMOVE_ALBUM';

export const PLAYLIST_START = 'PLAYLIST_START';
export const PLAYLIST_CANCEL = 'PLAYLIST_CANCEL';
